/**
 * Application-generated identifiers.
 *
 * Portable SQL Contract item 1 (suite `020`, binding on new Long Tua tables
 * per `090` item 6): IDs are generated by the application (UUIDv7 strings),
 * never by the database — no sequences, no reliance on `gen_random_uuid()`.
 * UUIDv7 is time-ordered, so it indexes like a monotonic key on both Postgres
 * and MySQL-family engines while staying a plain 36-char `text` column.
 *
 * Ported from `@suite/db-core/src/ids.ts` (the suite package is not published
 * to this repo). Keep the two implementations byte-compatible: same layout,
 * same version/variant bits, so ids are indistinguishable across the suite.
 *
 * Existing tables keep the shared `uuid("id").defaultRandom()` helper in
 * `schema.ts` — they predate the contract and re-key opportunistically, not
 * wholesale. Only NEW tables use `newId`.
 */

const HEX: string[] = Array.from({ length: 256 }, (_, i) =>
  i.toString(16).padStart(2, "0")
);

/**
 * Generate a UUIDv7 string: 48-bit big-endian Unix ms timestamp, version 7,
 * RFC 4122 variant, 74 random bits.
 */
export function newId(): string {
  const bytes = new Uint8Array(16);
  globalThis.crypto.getRandomValues(bytes);

  const ts = Date.now();
  bytes[0] = Math.floor(ts / 2 ** 40) & 0xff;
  bytes[1] = Math.floor(ts / 2 ** 32) & 0xff;
  bytes[2] = Math.floor(ts / 2 ** 24) & 0xff;
  bytes[3] = Math.floor(ts / 2 ** 16) & 0xff;
  bytes[4] = Math.floor(ts / 2 ** 8) & 0xff;
  bytes[5] = ts & 0xff;

  // version 7
  bytes[6] = (bytes[6] & 0x0f) | 0x70;
  // RFC 4122 variant
  bytes[8] = (bytes[8] & 0x3f) | 0x80;

  const h = (i: number): string => HEX[bytes[i]];
  return (
    h(0) + h(1) + h(2) + h(3) +
    "-" + h(4) + h(5) +
    "-" + h(6) + h(7) +
    "-" + h(8) + h(9) +
    "-" + h(10) + h(11) + h(12) + h(13) + h(14) + h(15)
  );
}
