import type { Database } from "../index";
import { whtRates } from "../schema";

/**
 * WHT rate seed data based on Thai Revenue Department Section 40 payment types.
 * Rates effective as of 2024. e-WHT reduced rates valid through 2025-12-31.
 */
export const whtRateSeedData = [
  // ---- Domestic: Individual (PND 3) ----
  {
    paymentType: "service",
    entityType: "individual" as const,
    rdPaymentTypeCode: "40(8)",
    standardRate: "0.0300",
    ewhtRate: null,
    ewhtValidFrom: null,
    ewhtValidTo: null,
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "professional_fees",
    entityType: "individual" as const,
    rdPaymentTypeCode: "40(6)",
    standardRate: "0.0300",
    ewhtRate: null,
    ewhtValidFrom: null,
    ewhtValidTo: null,
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "rent_immovable",
    entityType: "individual" as const,
    rdPaymentTypeCode: "40(5)(a)",
    standardRate: "0.0500",
    ewhtRate: null,
    ewhtValidFrom: null,
    ewhtValidTo: null,
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "rent_other",
    entityType: "individual" as const,
    rdPaymentTypeCode: "40(5)(a)",
    standardRate: "0.0500",
    ewhtRate: null,
    ewhtValidFrom: null,
    ewhtValidTo: null,
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "advertising",
    entityType: "individual" as const,
    rdPaymentTypeCode: "40(8)",
    standardRate: "0.0200",
    ewhtRate: null,
    ewhtValidFrom: null,
    ewhtValidTo: null,
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "transport",
    entityType: "individual" as const,
    rdPaymentTypeCode: "40(8)",
    standardRate: "0.0100",
    ewhtRate: null,
    ewhtValidFrom: null,
    ewhtValidTo: null,
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "insurance_premium",
    entityType: "individual" as const,
    rdPaymentTypeCode: "40(8)",
    standardRate: "0.0100",
    ewhtRate: null,
    ewhtValidFrom: null,
    ewhtValidTo: null,
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "royalties",
    entityType: "individual" as const,
    rdPaymentTypeCode: "40(3)",
    standardRate: "0.0300",
    ewhtRate: null,
    ewhtValidFrom: null,
    ewhtValidTo: null,
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "prizes",
    entityType: "individual" as const,
    rdPaymentTypeCode: "40(8)",
    standardRate: "0.0500",
    ewhtRate: null,
    ewhtValidFrom: null,
    ewhtValidTo: null,
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "interest",
    entityType: "individual" as const,
    rdPaymentTypeCode: "40(4)(a)",
    standardRate: "0.1500",
    ewhtRate: null,
    ewhtValidFrom: null,
    ewhtValidTo: null,
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "dividends",
    entityType: "individual" as const,
    rdPaymentTypeCode: "40(4)(b)",
    standardRate: "0.1000",
    ewhtRate: null,
    ewhtValidFrom: null,
    ewhtValidTo: null,
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },

  // ---- Domestic: Company (PND 53) ----
  {
    paymentType: "service",
    entityType: "company" as const,
    rdPaymentTypeCode: "40(8)",
    standardRate: "0.0300",
    ewhtRate: "0.0200",
    ewhtValidFrom: "2020-10-01",
    ewhtValidTo: "2025-12-31",
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "professional_fees",
    entityType: "company" as const,
    rdPaymentTypeCode: "40(6)",
    standardRate: "0.0300",
    ewhtRate: "0.0200",
    ewhtValidFrom: "2020-10-01",
    ewhtValidTo: "2025-12-31",
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "rent_immovable",
    entityType: "company" as const,
    rdPaymentTypeCode: "40(5)(a)",
    standardRate: "0.0500",
    ewhtRate: "0.0300",
    ewhtValidFrom: "2020-10-01",
    ewhtValidTo: "2025-12-31",
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "rent_other",
    entityType: "company" as const,
    rdPaymentTypeCode: "40(5)(a)",
    standardRate: "0.0500",
    ewhtRate: "0.0300",
    ewhtValidFrom: "2020-10-01",
    ewhtValidTo: "2025-12-31",
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "advertising",
    entityType: "company" as const,
    rdPaymentTypeCode: "40(8)",
    standardRate: "0.0200",
    ewhtRate: "0.0200",
    ewhtValidFrom: "2020-10-01",
    ewhtValidTo: "2025-12-31",
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "transport",
    entityType: "company" as const,
    rdPaymentTypeCode: "40(8)",
    standardRate: "0.0100",
    ewhtRate: "0.0100",
    ewhtValidFrom: "2020-10-01",
    ewhtValidTo: "2025-12-31",
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "insurance_premium",
    entityType: "company" as const,
    rdPaymentTypeCode: "40(8)",
    standardRate: "0.0100",
    ewhtRate: "0.0100",
    ewhtValidFrom: "2020-10-01",
    ewhtValidTo: "2025-12-31",
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "royalties",
    entityType: "company" as const,
    rdPaymentTypeCode: "40(3)",
    standardRate: "0.0300",
    ewhtRate: "0.0200",
    ewhtValidFrom: "2020-10-01",
    ewhtValidTo: "2025-12-31",
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "prizes",
    entityType: "company" as const,
    rdPaymentTypeCode: "40(8)",
    standardRate: "0.0500",
    ewhtRate: "0.0300",
    ewhtValidFrom: "2020-10-01",
    ewhtValidTo: "2025-12-31",
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "interest",
    entityType: "company" as const,
    rdPaymentTypeCode: "40(4)(a)",
    standardRate: "0.0100",
    ewhtRate: "0.0100",
    ewhtValidFrom: "2020-10-01",
    ewhtValidTo: "2025-12-31",
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "dividends",
    entityType: "company" as const,
    rdPaymentTypeCode: "40(4)(b)",
    standardRate: "0.1000",
    ewhtRate: null,
    ewhtValidFrom: null,
    ewhtValidTo: null,
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },

  // ---- Foreign (PND 54) ----
  {
    paymentType: "service_fees",
    entityType: "foreign" as const,
    rdPaymentTypeCode: "40(8)",
    standardRate: "0.1500",
    ewhtRate: null,
    ewhtValidFrom: null,
    ewhtValidTo: null,
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "royalties",
    entityType: "foreign" as const,
    rdPaymentTypeCode: "40(3)",
    standardRate: "0.1500",
    ewhtRate: null,
    ewhtValidFrom: null,
    ewhtValidTo: null,
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "interest",
    entityType: "foreign" as const,
    rdPaymentTypeCode: "40(4)(a)",
    standardRate: "0.1500",
    ewhtRate: null,
    ewhtValidFrom: null,
    ewhtValidTo: null,
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "dividends",
    entityType: "foreign" as const,
    rdPaymentTypeCode: "40(4)(b)",
    standardRate: "0.1000",
    ewhtRate: null,
    ewhtValidFrom: null,
    ewhtValidTo: null,
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "capital_gains",
    entityType: "foreign" as const,
    rdPaymentTypeCode: "40(4)(c)",
    standardRate: "0.1500",
    ewhtRate: null,
    ewhtValidFrom: null,
    ewhtValidTo: null,
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "rent",
    entityType: "foreign" as const,
    rdPaymentTypeCode: "40(5)(a)",
    standardRate: "0.1500",
    ewhtRate: null,
    ewhtValidFrom: null,
    ewhtValidTo: null,
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
  {
    paymentType: "technical_management_fees",
    entityType: "foreign" as const,
    rdPaymentTypeCode: "40(8)",
    standardRate: "0.1500",
    ewhtRate: null,
    ewhtValidFrom: null,
    ewhtValidTo: null,
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
  },
];

export async function seedWhtRates(db: Database) {
  console.log("Seeding WHT rates...");
  await db.insert(whtRates).values(whtRateSeedData).onConflictDoNothing();
  console.log(`Seeded ${whtRateSeedData.length} WHT rate entries.`);
}
