import type { glAccounts } from "@/lib/db/schema";

export type StandardGlAccountSeed = Omit<
  typeof glAccounts.$inferInsert,
  "id" | "orgId" | "createdAt" | "updatedAt" | "deletedAt"
>;

export const STANDARD_THAI_COA: StandardGlAccountSeed[] = [
  {
    accountCode: "1111",
    nameTh: "เงินฝากธนาคาร - บัญชีกระแสรายวัน",
    nameEn: "Bank - operating account",
    accountType: "asset",
    accountSubtype: "bank",
    isSystem: true,
    isPostable: true,
  },
  {
    accountCode: "1140",
    nameTh: "ลูกหนี้การค้า",
    nameEn: "Trade accounts receivable",
    accountType: "asset",
    accountSubtype: "ar",
    isControlAccount: true,
    isSystem: true,
  },
  {
    accountCode: "1142",
    nameTh: "ลูกหนี้รอรับชำระจากช่องทางขาย",
    nameEn: "Processor / marketplace settlement receivable",
    accountType: "asset",
    accountSubtype: "clearing",
    isClearing: true,
    isSystem: true,
  },
  {
    accountCode: "1160",
    nameTh: "สินค้าคงเหลือ - สินค้าสำเร็จรูป",
    nameEn: "Inventory - merchandise",
    accountType: "asset",
    accountSubtype: "inventory",
    isControlAccount: true,
    isAutomated: true,
    isSystem: true,
  },
  {
    accountCode: "1180",
    nameTh: "ภาษีหัก ณ ที่จ่ายรอขอคืน",
    nameEn: "Prepaid withholding tax",
    accountType: "asset",
    accountSubtype: "tax_receivable",
    isControlAccount: true,
    isAutomated: true,
    isSystem: true,
    taxTreatment: "n_a",
    whtRegisterRole: "wht_credits_receivable",
  },
  {
    accountCode: "1185",
    nameTh: "เงินจ่ายล่วงหน้าค่าสินค้านำเข้า",
    nameEn: "Supplier advances - imports",
    accountType: "asset",
    accountSubtype: "prepaid",
    isClearing: true,
    isAutomated: true,
    isSystem: true,
    taxTreatment: "n_a",
  },
  {
    accountCode: "1186",
    nameTh: "ภาษีเงินได้นิติบุคคลจ่ายล่วงหน้า",
    nameEn: "Prepaid corporate income tax",
    accountType: "asset",
    accountSubtype: "tax_receivable",
    isControlAccount: true,
    isAutomated: true,
    isSystem: true,
    taxTreatment: "n_a",
  },
  {
    accountCode: "1251",
    nameTh: "ภาษีซื้อขอคืนได้",
    nameEn: "Input VAT recoverable",
    accountType: "asset",
    accountSubtype: "tax_receivable",
    isControlAccount: true,
    isAutomated: true,
    isSystem: true,
    taxTreatment: "vat_recoverable_input",
    vatRegisterRole: "input_tax_recoverable",
  },
  {
    accountCode: "1253",
    nameTh: "ภาษีซื้อ ภ.พ. 36 รอเรียกคืน",
    nameEn: "Input VAT - PP36 pending reclaim",
    accountType: "asset",
    accountSubtype: "tax_receivable",
    isControlAccount: true,
    isAutomated: true,
    isSystem: true,
    taxTreatment: "vat_recoverable_input",
    vatRegisterRole: "pp36_reclaim",
  },
  {
    accountCode: "1310",
    nameTh: "ที่ดิน",
    nameEn: "Land",
    accountType: "asset",
    accountSubtype: "fixed_asset",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "1320",
    nameTh: "อาคาร",
    nameEn: "Buildings",
    accountType: "asset",
    accountSubtype: "fixed_asset",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "1330",
    nameTh: "อุปกรณ์",
    nameEn: "Equipment",
    accountType: "asset",
    accountSubtype: "fixed_asset",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "1340",
    nameTh: "ยานพาหนะ",
    nameEn: "Vehicles",
    accountType: "asset",
    accountSubtype: "fixed_asset",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "1350",
    nameTh: "คอมพิวเตอร์และอุปกรณ์",
    nameEn: "Computer equipment",
    accountType: "asset",
    accountSubtype: "fixed_asset",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "1360",
    nameTh: "เครื่องตกแต่งและติดตั้ง",
    nameEn: "Furniture and fixtures",
    accountType: "asset",
    accountSubtype: "fixed_asset",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "1420",
    nameTh: "สินทรัพย์ไม่มีตัวตน - ซอฟต์แวร์",
    nameEn: "Intangible assets - software",
    accountType: "asset",
    accountSubtype: "fixed_asset",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "1421",
    nameTh: "ค่าตัดจำหน่ายสะสม - สินทรัพย์ไม่มีตัวตน",
    nameEn: "Accumulated amortization - intangible assets",
    accountType: "asset",
    accountSubtype: "contra_fixed_asset",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "1430",
    nameTh: "สิทธิในทรัพยากรธรรมชาติ",
    nameEn: "Natural resource rights",
    accountType: "asset",
    accountSubtype: "fixed_asset",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "1431",
    nameTh: "ค่าสูญสิ้นสะสม - สิทธิในทรัพยากรธรรมชาติ",
    nameEn: "Accumulated depletion - natural resource rights",
    accountType: "asset",
    accountSubtype: "contra_fixed_asset",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "1321",
    nameTh: "ค่าเสื่อมราคาสะสม - อาคาร",
    nameEn: "Accumulated depreciation - buildings",
    accountType: "asset",
    accountSubtype: "contra_fixed_asset",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "1331",
    nameTh: "ค่าเสื่อมราคาสะสม - อุปกรณ์",
    nameEn: "Accumulated depreciation - equipment",
    accountType: "asset",
    accountSubtype: "contra_fixed_asset",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "1341",
    nameTh: "ค่าเสื่อมราคาสะสม - ยานพาหนะ",
    nameEn: "Accumulated depreciation - vehicles",
    accountType: "asset",
    accountSubtype: "contra_fixed_asset",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "1351",
    nameTh: "ค่าเสื่อมราคาสะสม - คอมพิวเตอร์",
    nameEn: "Accumulated depreciation - computer",
    accountType: "asset",
    accountSubtype: "contra_fixed_asset",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "1361",
    nameTh: "ค่าเสื่อมราคาสะสม - เครื่องตกแต่ง",
    nameEn: "Accumulated depreciation - furniture and fixtures",
    accountType: "asset",
    accountSubtype: "contra_fixed_asset",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "2110",
    nameTh: "เจ้าหนี้การค้า",
    nameEn: "Trade accounts payable",
    accountType: "liability",
    accountSubtype: "ap",
    isControlAccount: true,
    isSystem: true,
  },
  {
    accountCode: "2150",
    nameTh: "ภาษีขาย",
    nameEn: "Output VAT payable",
    accountType: "liability",
    accountSubtype: "tax_payable",
    isControlAccount: true,
    isAutomated: true,
    isSystem: true,
    vatRegisterRole: "output_tax_payable",
  },
  {
    accountCode: "2151",
    nameTh: "ภาษีมูลค่าเพิ่มค้างจ่าย ภ.พ. 30",
    nameEn: "Output VAT payable - PP30 net",
    accountType: "liability",
    accountSubtype: "tax_payable",
    isControlAccount: true,
    isAutomated: true,
    isSystem: true,
    vatRegisterRole: "output_tax_payable",
  },
  {
    accountCode: "2152",
    nameTh: "ภาษีมูลค่าเพิ่มค้างจ่าย ภ.พ. 36",
    nameEn: "PP36 self-assessed VAT payable",
    accountType: "liability",
    accountSubtype: "tax_payable",
    isControlAccount: true,
    isAutomated: true,
    isSystem: true,
    vatRegisterRole: "pp36_payable",
  },
  {
    accountCode: "2153",
    nameTh: "ภาษีหัก ณ ที่จ่ายค้างจ่าย ภ.ง.ด.3",
    nameEn: "WHT payable - PND.3",
    accountType: "liability",
    accountSubtype: "tax_payable",
    isControlAccount: true,
    isAutomated: true,
    isSystem: true,
    whtRegisterRole: "wht_payable_pnd3",
  },
  {
    accountCode: "2154",
    nameTh: "ภาษีหัก ณ ที่จ่ายค้างจ่าย ภ.ง.ด.53",
    nameEn: "WHT payable - PND.53",
    accountType: "liability",
    accountSubtype: "tax_payable",
    isControlAccount: true,
    isAutomated: true,
    isSystem: true,
    whtRegisterRole: "wht_payable_pnd53",
  },
  {
    accountCode: "2155",
    nameTh: "ภาษีหัก ณ ที่จ่ายค้างจ่าย ภ.ง.ด.54",
    nameEn: "WHT payable - PND.54",
    accountType: "liability",
    accountSubtype: "tax_payable",
    isControlAccount: true,
    isAutomated: true,
    isSystem: true,
    whtRegisterRole: "wht_payable_pnd54",
  },
  {
    accountCode: "2156",
    nameTh: "ภาษีหัก ณ ที่จ่ายค้างจ่าย ภ.ง.ด.1",
    nameEn: "WHT payable - PND.1",
    accountType: "liability",
    accountSubtype: "tax_payable",
    isControlAccount: true,
    isAutomated: true,
    isSystem: true,
    whtRegisterRole: "wht_payable_pnd1",
  },
  {
    accountCode: "2157",
    nameTh: "เงินประกันสังคมค้างจ่าย",
    nameEn: "SSO payable",
    accountType: "liability",
    accountSubtype: "payroll_payable",
    isControlAccount: true,
    isAutomated: true,
    isSystem: true,
  },
  {
    accountCode: "2158",
    nameTh: "เงินเดือนและค่าจ้างค้างจ่าย",
    nameEn: "Salaries and wages payable",
    accountType: "liability",
    accountSubtype: "payroll_payable",
    isControlAccount: true,
    isAutomated: true,
    isSystem: true,
  },
  {
    accountCode: "2159",
    nameTh: "กองทุนสำรองเลี้ยงชีพค้างจ่าย",
    nameEn: "Provident fund payable",
    accountType: "liability",
    accountSubtype: "payroll_payable",
    isControlAccount: true,
    isAutomated: true,
    isSystem: true,
  },
  {
    accountCode: "2170",
    nameTh: "ภาษีเงินได้นิติบุคคลค้างจ่าย",
    nameEn: "Corporate income tax payable",
    accountType: "liability",
    accountSubtype: "tax_payable",
    isControlAccount: true,
    isAutomated: true,
    isSystem: true,
  },
  {
    accountCode: "2190",
    nameTh: "หนี้สินหมุนเวียนอื่น",
    nameEn: "Other current liabilities",
    accountType: "liability",
    accountSubtype: "other_current_liability",
    isAutomated: true,
    isSystem: true,
  },
  {
    accountCode: "3110",
    nameTh: "ทุนเรือนหุ้น",
    nameEn: "Share capital",
    accountType: "equity",
    accountSubtype: "equity_capital",
    isSystem: true,
  },
  {
    accountCode: "3210",
    nameTh: "กำไรสะสม",
    nameEn: "Retained earnings",
    accountType: "equity",
    accountSubtype: "retained_earnings",
    isSystem: true,
  },
  {
    accountCode: "3220",
    nameTh: "กำไรสะสม",
    nameEn: "Retained earnings",
    accountType: "equity",
    accountSubtype: "retained_earnings",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "3230",
    nameTh: "กำไร(ขาดทุน)งวดปัจจุบัน",
    nameEn: "Current year profit or loss",
    accountType: "equity",
    accountSubtype: "income_summary",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "4110",
    nameTh: "รายได้จากการขาย",
    nameEn: "Sales revenue",
    accountType: "revenue",
    accountSubtype: "sales",
    isSystem: true,
    taxTreatment: "taxable_revenue",
  },
  {
    accountCode: "4330",
    nameTh: "กำไรจากอัตราแลกเปลี่ยน",
    nameEn: "Foreign exchange gain",
    accountType: "revenue",
    accountSubtype: "fx_gain",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "4340",
    nameTh: "กำไรจากการจำหน่ายสินทรัพย์",
    nameEn: "Gain on disposal of assets",
    accountType: "revenue",
    accountSubtype: "asset_disposal_gain",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "5110",
    nameTh: "ต้นทุนขาย",
    nameEn: "Cost of goods sold",
    accountType: "cogs",
    accountSubtype: "cogs_inventory",
    isSystem: true,
  },
  {
    accountCode: "5120",
    nameTh: "ผลต่างสินค้าคงเหลือ",
    nameEn: "Inventory adjustments and shrinkage",
    accountType: "cogs",
    accountSubtype: "inventory_adjustments",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "5150",
    nameTh: "ภาษีศุลกากร",
    nameEn: "Customs duty",
    accountType: "cogs",
    accountSubtype: "import_duty",
    isSystem: true,
    isAutomated: true,
    taxTreatment: "n_a",
  },
  {
    accountCode: "5160",
    nameTh: "ค่าขนส่งและพิธีการศุลกากรขาเข้า",
    nameEn: "Inbound freight and brokerage",
    accountType: "cogs",
    accountSubtype: "import_overhead",
    isSystem: true,
    isAutomated: true,
    taxTreatment: "n_a",
  },
  {
    accountCode: "6110",
    nameTh: "เงินเดือนและค่าจ้าง",
    nameEn: "Salaries and wages",
    accountType: "expense",
    accountSubtype: "salaries",
    isSystem: true,
  },
  {
    accountCode: "6112",
    nameTh: "ค่าใช้จ่ายประกันสังคม - นายจ้าง",
    nameEn: "Social security expense - employer",
    accountType: "expense",
    accountSubtype: "payroll_expense",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "6113",
    nameTh: "ค่าใช้จ่ายกองทุนสำรองเลี้ยงชีพ - นายจ้าง",
    nameEn: "Provident fund expense - employer",
    accountType: "expense",
    accountSubtype: "payroll_expense",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "6610",
    nameTh: "ค่ารับรอง",
    nameEn: "Entertainment and representation expense",
    accountType: "expense",
    accountSubtype: "entertainment",
    isSystem: true,
    taxTreatment: "n_a",
  },
  {
    accountCode: "6411",
    nameTh: "ค่าธรรมเนียมรับชำระ",
    nameEn: "Payment gateway / card-processing fees",
    accountType: "expense",
    accountSubtype: "merchant_fees",
    isSystem: true,
    isAutomated: true,
    taxTreatment: "n_a",
  },
  {
    accountCode: "6810",
    nameTh: "ค่าใช้จ่ายภาษีเงินได้นิติบุคคล",
    nameEn: "Corporate income tax expense",
    accountType: "expense",
    accountSubtype: "income_tax",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "6820",
    nameTh: "ค่าเสื่อมราคา - อาคาร",
    nameEn: "Depreciation - buildings",
    accountType: "expense",
    accountSubtype: "depreciation",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "6821",
    nameTh: "ค่าเสื่อมราคา - อุปกรณ์",
    nameEn: "Depreciation - equipment",
    accountType: "expense",
    accountSubtype: "depreciation",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "6822",
    nameTh: "ค่าเสื่อมราคา - ยานพาหนะ",
    nameEn: "Depreciation - vehicles",
    accountType: "expense",
    accountSubtype: "depreciation",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "6823",
    nameTh: "ค่าเสื่อมราคา - คอมพิวเตอร์",
    nameEn: "Depreciation - computer",
    accountType: "expense",
    accountSubtype: "depreciation",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "6824",
    nameTh: "ค่าเสื่อมราคา - เครื่องตกแต่ง",
    nameEn: "Depreciation - furniture and fixtures",
    accountType: "expense",
    accountSubtype: "depreciation",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "6825",
    nameTh: "ค่าตัดจำหน่าย - สินทรัพย์ไม่มีตัวตน",
    nameEn: "Amortization - intangible assets",
    accountType: "expense",
    accountSubtype: "depreciation",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "6826",
    nameTh: "ค่าสูญสิ้น - สิทธิในทรัพยากรธรรมชาติ",
    nameEn: "Depletion - natural resource rights",
    accountType: "expense",
    accountSubtype: "depreciation",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "6870",
    nameTh: "ขาดทุนจากอัตราแลกเปลี่ยน",
    nameEn: "Foreign exchange loss",
    accountType: "expense",
    accountSubtype: "fx_loss",
    isSystem: true,
    isAutomated: true,
  },
  {
    accountCode: "6880",
    nameTh: "ขาดทุนจากการจำหน่ายสินทรัพย์",
    nameEn: "Loss on disposal of assets",
    accountType: "expense",
    accountSubtype: "asset_disposal_loss",
    isSystem: true,
    isAutomated: true,
  },
];
